### ISSUE TITLE
error

### ISSUE THREAD

**Issue by jisamcom** [Kayakflo/wow-dialogkey-sl#2]
1st and 2nd were not completed quest return, and 3rd one is completed, and i got this error.

`2x DialogKey\main.lua:245: attempt to index field '?' (a nil value)
[string "@DialogKey\main.lua"]:245: in function `ClickButtons'
[string "@DialogKey\main.lua"]:195: in function <DialogKey\main.lua:134>

Locals:
self = <table> {
 SetDefaultModuleLibraries = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:367
 DisableQuestScrolling = <function> defined @DialogKey\main.lua:465
 EnableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:332
 modules = <table> {
 }
 CancelTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:147
 ClickFrameName = <function> defined @DialogKey\main.lua:329
 keybindIndex = 0
 recentlyPressed = false
 Printf = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:69
 SetDefaultModulePrototype = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:409
 HandleScroll = <function> defined @DialogKey\main.lua:479
 defaultModuleState = true
 IsEnabled = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:451
 ScheduleTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:94
 DisableModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:350
 Glow = <function> defined @DialogKey\main.lua:413
 RegisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 ClickFrame = <function> defined @DialogKey\main.lua:271
 scrollFrames = <table> {
 }
 db = <table> {
 }
 GlowQuestIndex = <function> defined @DialogKey\main.lua:434
 SetEnabledState = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:424
 enabledState = true
 RegisterEvent = <function> defined @Ace3\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 IterateModules = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:437
 ClickButtons = <function> defined @DialogKey\main.lua:212
 frame = DialogKeyFrame {
 }
 RemoveMouseFocus = <function> defined @DialogKey\main.lua:72
 AddMouseFocus = <function> defined @DialogKey\main.lua:2
 debug_dialog = <function> defined @DialogKey\main.lua:502
 OnInitialize = <function> defined @DialogKey\core.lua:67
 NewModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:235
 glowFrame = DialogKeyGlow {
 }
 GetModule = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:210
 round = <function> defined @DialogKey\core.lua:216
 FindPathTo = <function> defined @DialogKey\main.lua:21
 options = <unnamed> {
 }
 UnregisterChatCommand = <function> defined @Ace3\AceConsole-3.0\AceConsole-3.0.lua:111
 ValueToString = <function> defined @DialogKey\options.lua:483
 ScheduleRepeatingTimer = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:129
 CancelAllTimers = <function> defined @Ace3\AceTimer-3.0\AceTimer-3.0.lua:160
 keybindMode = false
 UnwatchFrame = <function> defined @DialogKey\main.lua:110
 GetName = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:279
 EnumerateGossips_Quest = <function> defined @DialogKey\main.lua:375
 baseName = "DialogKey"
 UpdateBlacklist = <function> defined @DialogKey\options.lua:476
 name = "DialogKey"
 SaveBlacklist = <function> defined @DialogKey\options.lua:460
 UpdateAdditionalFrames = <function> defined @DialogKey\options.lua:453
 ShowOldKeybindWarning = <function> defined @DialogKey\core.lua:142
 IterateEmbeds = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:442
 Disable = <function> defined @Ace3\AceAddon-3.0\AceAddon-3.0.lua:314
 GetFrameByName = <function> defined @DialogKey\main.lua:56
 builtinDialogBlacklist = <table> {
 }
 HandleKeybind = <function> defined @DialogKey\option`

**Comment by jisamcom** [comment]
fixed myself.. actually...

due to change of gossipframe 

https://github.com/tomrus88/BlizzardInterfaceCode/blob/master/Interface/FrameXML/GossipFrame.lua

changed to line 246 ~ 258

```
			for i=1,9 do
				if GossipFrame_GetTitleButton(i) then
					if GossipFrame_GetTitleButton(i).Icon:IsVisible() and (
						GossipFrame_GetTitleButton(i).Icon:GetTexture() == "Interface/GossipFrame/ActiveQuestIcon" or
						GossipFrame_GetTitleButton(i).Icon:GetTexture() == "Interface/GossipFrame/ActiveLegendaryQuestIcon") then
					
						return DialogKey:ClickFrame(GossipFrame_GetTitleButton(i))
					end
				end
			end
			
			-- If none were found, just click the first one
			return DialogKey:ClickFrame(GossipFrame_GetTitleButton(1))
```

**Comment by Kayakflo** [comment]
Thank you @jisamcom not only for the report but also for the follow up fix!
I have merged your suggestion and created a new release.
